### ISSUE TITLE
vgg16 has 13 conv layers, how can you prune neurons on layer 28?

### ISSUE THREAD

**Issue by GuanhuaWang** [jacobgil/pytorch-pruning#27]

**Comment by mashrurmorshed** [comment]
The layers do not specifically allude to 'conv' layers. VGG16 has 31 layers, among which 13 are conv layers as you already know. The other layers consist of maxpools and relus. If you execute the following code:

from torchvision import models
model = models.vgg16()
print(model.features)

You will obtain a list of layers, from 0 to 30. Layer 28, in fact, is the last conv layer.

**Comment by GuanhuaWang** [comment]
thx
