### ISSUE TITLE
RuntimeError: dimension out of range (expected to be in range of [-2, 1], but got 3)

### ISSUE THREAD

**Issue by pgadosey** [jacobgil/pytorch-pruning#6]
Hi Jacob, I get this error when i run finetune.py --prune

Traceback (most recent call last):
  File "fine_tune.py", line 271, in <module>
    fine_tuner.prune()
  File "fine_tune.py", line 218, in prune
    prune_targets = self.get_candidates_to_prune(num_filters_to_prune_per_iteration)
  File "fine_tune.py", line 184, in get_candidates_to_prune
    self.train_epoch(rank_filters = True)
  File "fine_tune.py", line 179, in train_epoch
    self.train_batch(optimizer, batch.cuda(), label.cuda(), rank_filters)
  File "fine_tune.py", line 172, in train_batch
    self.criterion(output, Variable(label)).backward()
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/variable.py", line 156, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/__init__.py", line 98, in backward
    variables, grad_variables, retain_graph)
  File "fine_tune.py", line 77, in compute_rank
    sum(dim=2).sum(dim=3)[0, :, 0, 0].data
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/variable.py", line 476, in sum
    return Sum.apply(self, dim, keepdim)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/_functions/reduce.py", line 21, in forward
    return input.sum(dim)
RuntimeError: dimension out of range (expected to be in range of [-2, 1], but got 3)

I have not been able to figure out exactly what's causing the error

**Comment by eeric** [comment]
so did I

**Comment by jacobgil** [comment]
Hi I will check this and get back with an answer during the next few days.
What version of Pytorch are you using?

`import torch`
`print torch.__version__`

**Comment by eeric** [comment]
0.2.0_1, mine, failed

0.1.12_2, my friend, yet he succeeded.

**Comment by pgadosey** [comment]
mine is 0.2.0_1 as well...Does it have anything to do with the pytorch version?

**Comment by pgadosey** [comment]
keepdim in torch.sum has a default value of None, I changed it to True and that seems to have solved the issue

**Comment by eeric** [comment]
@pgadosey , where in finetune.py modified?

**Comment by BUPTLdy** [comment]
@eeric 
I have encountered this problem, have you fix it? Thank you

**Comment by eeric** [comment]
@BUPTLdy , Not solved, and I sitll used torch version 0.1.12_2

**Comment by BUPTLdy** [comment]
@eeric Thanks for your reply, I solved it by setting `bias = True` in file prune.py.

**Comment by eeric** [comment]
ok, but for ResNet model, error setting

**Comment by eeric** [comment]
@BUPTLdy, setting bias = True in file prune.py, in detail？

**Comment by BUPTLdy** [comment]
@eeric 
In lines 33 and 58 in file prune.py, change to `bias = True`.

**Comment by eeric** [comment]
@BUPTLdy, oh, but it occured error for vgg convolution layer inheritance, and What is more, ResNet

**Comment by promach** [comment]
> @eeric
> In lines 33 and 58 in file prune.py, change to `bias = True`.

Why set `bias = True` in those two lines ?

Besides, modifying the code according to your advice does not solve the problem, same error still persists.

**Comment by Anurag0212** [comment]
> keepdim in torch.sum has a default value of None, I changed it to True and that seems to have solved the issue

I couldn't find the keepdim in torch.sum, Could you please share the line number?

**Comment by promach** [comment]
@Anurag0212 I have done the modification at https://github.com/promach/pytorch-pruning/ . You could just use the repo. I am still trying to figure out how to test the model_prunned given some classes.

**Comment by Mouatassem1** [comment]
RuntimeError                              Traceback (most recent call last)
<ipython-input-25-55d5cacbd21e> in <module>()
     23     # convert output probabilities to predicted class
     24     #_, pred = torch.max(output, 1)
---> 25     _, pred = torch.max(output, dim=1)
     26     # compare predictions to true label
     27     correct_tensor = pred.eq(target.data.view_as(pred))

RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

**Comment by Mouatassem1** [comment]
RuntimeError                              Traceback (most recent call last)
<ipython-input-25-55d5cacbd21e> in <module>()
     23     # convert output probabilities to predicted class
     24     #_, pred = torch.max(output, 1)
---> 25     _, pred = torch.max(output, dim=1)
     26     # compare predictions to true label
     27     correct_tensor = pred.eq(target.data.view_as(pred))

RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
